server:
  addr: "0.0.0.0:80"
app:
  name: "dazed and confuzed"
  log_level: "INFO"
  root_password: "password"
postgres:
  url: "localhost:5432"
  user: "user"
  password: "user"
  db: "dazed_db"
  ssl_mode: "disable"
  migrations_path: "file://migrations"
redis:
  db: 0
  url: "localhost:6379"
  password: ""